<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-05-18T23:13:45 IST" name="Default suite" finished-at="2024-05-18T23:14:36 IST" duration-ms="51570">
    <groups>
    </groups>
    <test started-at="2024-05-18T23:13:45 IST" name="Default test" finished-at="2024-05-18T23:14:36 IST" duration-ms="51570">
      <class name="excelReading.DataDrivenTesting">
        <test-method is-config="true" signature="report()[pri:0, instance:excelReading.DataDrivenTesting@18df8434]" started-at="2024-05-18T23:13:45 IST" name="report" finished-at="2024-05-18T23:13:45 IST" duration-ms="231" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- report -->
        <test-method signature="testdatadriven(java.lang.String,java.lang.String)[pri:0, instance:excelReading.DataDrivenTesting@18df8434]" started-at="2024-05-18T23:13:45 IST" name="testdatadriven" data-provider="Excel" finished-at="2024-05-18T23:13:57 IST" duration-ms="11216" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[admin123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testdatadriven -->
        <test-method is-config="true" signature="amethod()[pri:0, instance:excelReading.DataDrivenTesting@18df8434]" started-at="2024-05-18T23:13:57 IST" name="amethod" finished-at="2024-05-18T23:13:57 IST" duration-ms="125" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- amethod -->
        <test-method signature="testdatadriven(java.lang.String,java.lang.String)[pri:0, instance:excelReading.DataDrivenTesting@18df8434]" started-at="2024-05-18T23:13:57 IST" name="testdatadriven" data-provider="Excel" finished-at="2024-05-18T23:14:27 IST" duration-ms="30550" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Soumya]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Sanu123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login Failedcom.aventstack.extentreports.ExtentTest@2e179f3e expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login Failedcom.aventstack.extentreports.ExtentTest@2e179f3e expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at excelReading.DataDrivenTesting.testdatadriven(DataDrivenTesting.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testdatadriven -->
        <test-method is-config="true" signature="amethod()[pri:0, instance:excelReading.DataDrivenTesting@18df8434]" started-at="2024-05-18T23:14:27 IST" name="amethod" finished-at="2024-05-18T23:14:27 IST" duration-ms="129" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- amethod -->
        <test-method signature="testdatadriven(java.lang.String,java.lang.String)[pri:0, instance:excelReading.DataDrivenTesting@18df8434]" started-at="2024-05-18T23:14:27 IST" name="testdatadriven" data-provider="Excel" finished-at="2024-05-18T23:14:36 IST" duration-ms="8814" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Sanu]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Sanu123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login Failedcom.aventstack.extentreports.ExtentTest@2e179f3e expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login Failedcom.aventstack.extentreports.ExtentTest@2e179f3e expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at excelReading.DataDrivenTesting.testdatadriven(DataDrivenTesting.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testdatadriven -->
        <test-method is-config="true" signature="amethod()[pri:0, instance:excelReading.DataDrivenTesting@18df8434]" started-at="2024-05-18T23:14:36 IST" name="amethod" finished-at="2024-05-18T23:14:36 IST" duration-ms="126" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- amethod -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:excelReading.DataDrivenTesting@18df8434]" started-at="2024-05-18T23:14:36 IST" name="tearDown" finished-at="2024-05-18T23:14:37 IST" duration-ms="311" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- excelReading.DataDrivenTesting -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
